config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :profile , :only => [:index] do
    collection do
      post :save
    end
  end

  resources :game , :only => [:show] do
    collection do
      get  'about'
    end
    member do
      post 'level_callback'
      get  'level'
      post 'level_save'
      get  'level_show'
    end
  end

  root 'game#index'

end

app/models/score.rb
class Score < ActiveRecord::Base
  LEVEL_COUNT = 9
  TWITTER_LEVEL = [0,1,2]

  def self.save_score(level , current_user , is_success , is_callback , source , result)
    temp = {:user_id => current_user.id , :level => level , :is_success => is_success , :is_callback => is_callback , :source => source , :result => result}

    score = Score.where(:user_id => current_user.id , :level => level).first
    if score
      score.update_attributes(temp)
    else
      score = Score.create(temp)
    end
    return score
  end
  def self.user_score(current_user)
    return ((Score.where(:user_id => current_user.id , :is_success => true).count.to_f / LEVEL_COUNT.to_f) * 100).to_i
  end
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  def self.get(name)
    Setting.where(name:name).first.value rescue nil
  end
  def self.set(name , value)
    setting = Setting.where(name:name).first
    if setting
      setting.update_attribute('name' , value)
    else
      Setting.create(name:name , value:value)
    end
  end
  def self.del(name)
    Setting.where(name:name).delete_all
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:name, :email, :password, :password_confirmation]
    if params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
end

app/controllers/game_controller.rb
require 'securerandom'
require 'timeout'
require 'open3'

class GameController < ApplicationController
  PATH = 'tmp/run_me'
  before_action :authenticate_user! , :except => [:about]
  skip_before_action :verify_authenticity_token , :only => [:level_callback]
  
#static page
  def index
    @title = 'Welcome'

    @games = {}
    Score.where(:user_id => current_user.id).each do |score|
      @games[score.level] = score
    end
  end
  def about
    @title = 'About'
  end
  
#game page
  
  def level
    @level = params[:id].to_i
  end
  def level_save
    @level = params[:id].to_i
    if Score::TWITTER_LEVEL.include?(@level)
      is_success , result = file_builder(params[:body] , :twitter)
      score = Score.save_score(@level , current_user , is_success , true , params[:body] , result)
    else
      score = Score.save_score(@level , current_user , false , false , params[:body] , params[:body])
    end
    redirect_to level_show_game_path(score.id)
  end
  def level_show
    @score = Score.where(:id => params[:id]).first
    redirect_to root_path unless @score
    @level = @score.level
    @message = @score.result
    @by_user = User.where(:id => @score.user_id).first
  end
  def level_callback
    Score.find(params[:id]).update_attributes(is_success:params['is_success'].to_i == 1,is_callback:true)
    render text:''
  end
  
  private
  
  def file_builder(body , content_type)
    return [false , "No content!"] unless body || body.empty?
    return [false , "Direct code injection! , can't use : (`|require|eval|Dir|system|gets|ENV|ARGF)"] if body.index(/(`|require|eval|Dir|system|gets|ENV|ARGF)/)

    Rails.logger.info `pwd`
    Rails.logger.info `ruby -v`
    Rails.logger.info `ls -al tmp/run_me`
    
    init_content = case content_type
    when :twitter
"require 'pp'
require 'twitter'
require 'open-uri'
require 'securerandom'

filename = SecureRandom.hex

$twitter_api = Twitter::REST::Client.new do |config|
  config.consumer_key        = '#{Setting.get('twitter_consumer_key')}'
  config.consumer_secret     = '#{Setting.get('twitter_consumer_secret')}'
  config.access_token        = '#{Setting.get('twitter_access_token')}'
  config.access_token_secret = '#{Setting.get('twitter_access_token_secret')}'
end"
    end
    
    
    @random_name = "#{PATH}/#{SecureRandom.hex}.rb"
    File.open(@random_name , 'w') do |f|
      f.write("
#{init_content}

#{body}
")
    end
    
    stdout_str , stderr_str , status = Open3.capture3("ruby #{@random_name}")
    begin
      Timeout::timeout(5) do
        while !status.exited?
          sleep(0.01)
        end
      end
    rescue
    end
    `kill -9 #{status.pid}` unless status.exited?

    success = false
    if status.success?
      success = stdout_str.length > 20
    end
    
    return [ !!success , status.success? ? stdout_str : stderr_str]
  ensure
    `rm #{@random_name}` if @random_name #clear
  end
  
  def check_status(index)
    session[:checked] ||= {}
    session[:checked][index.to_s] = true
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end
  def save
    current_user.update_attribute('name' , params[:name])
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def challenge_link(index)
    source = @games[index]
    if source
      (link_to 'result' , level_show_game_path(source.id) , class:'btn btn-info' ) + ' ' +
      if source.is_success
        link_to 'Successful , Replay »' , level_game_path(index) , class:'btn btn-success'
      else
        link_to 'Challenge fails , Replay »' , level_game_path(index) , class:'btn btn-warning'
      end
    else
      link_to 'Play »' , level_game_path(index) , class:'btn btn-warning'
    end
  end
end

app/views/game/_level_show_0.html.erb
<pre><%= @message %></pre>

app/views/game/_level_show_2.html.erb
<pre><%= @message %></pre>

app/views/game/_level_show_3.html.erb
<% content_for :js do %>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=geometry"></script>
  <script>
var map , geocoder;

function initialize() {
  var is_error = false;
  try{
    <%= raw(@message) %>
  }catch(e){
    is_error = true;
  }

  send_success(!is_error && map && geocoder , <%= @score.id %>);
}
google.maps.event.addDomListener(window, 'load', initialize);
    </script>
<% end %>

<div id="google_map" style="width:100%;height:400px;"></div>

app/views/game/_level_show_4.html.erb
<% content_for :js do %>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=geometry"></script>
  <script>
var map , geocoder;

function initialize() {
  var is_error = false;
  try{
    <%= raw(@message) %>
  }catch(e){
    is_error = true;
  }

  send_success(!is_error && map && geocoder , <%= @score.id %>);
  
}
google.maps.event.addDomListener(window, 'load', initialize);
    </script>
<% end %>

<pre id="timezone_show"></pre>

<div id="google_map" style="width:100%;height:400px;"></div>

app/views/game/_level_show_5.html.erb
<% content_for :js do %>
  <script>
  jQuery(function($){
    var is_success = false;
    try{

      <%= raw(@message) %>

      is_success = true;
    }catch(e){}

    send_success(is_success , <%= @score.id %>);

  });
  </script>
<% end %>

<p style="text-align:center;">
  <img id="qrcode"/>
</p>

app/views/game/_level_show_6.html.erb
<% content_for :js do %>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
  <script>
var panorama;

function initialize() {
  var is_error = false;
  try{
    <%= raw(@message) %>
  }catch(e){
    console.log(e);
    is_error = true;
  }

  send_success(!is_error && panorama, <%= @score.id %>);
  
}
google.maps.event.addDomListener(window, 'load', initialize);
    </script>
<% end %>

<div id="panorama" style="width:100%;height:400px;margin-bottom:300px;"></div>

app/views/game/_level_show_7.html.erb
<% content_for :js do %>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=geometry"></script>
  <script>
var map , panorama;

function initialize() {
  var is_error = false;
  try{
    <%= raw(@message) %>
  }catch(e){
    console.log(e);
    is_error = true;
  }

  send_success(!is_error && map && panorama, <%= @score.id %>);
  
}
google.maps.event.addDomListener(window, 'load', initialize);
    </script>
<% end %>

<pre id='map_info'></pre>
<div class='row' style="margin-bottom:300px;">
  <div id="google_map" style="width:30%;height:400px;float:left;"></div>
  <div id="panorama" style="width:69%;height:400px;float:right;"></div>
</div>

app/views/game/_level_show_8.html.erb
<% content_for :js do %>
  <script>
  jQuery(function($){
    var is_success = false;
    try{

      <%= raw(@message) %>

      is_success = true;
    }catch(e){}

    send_success(is_success , <%= @score.id %>);

  });
  </script>
<% end %>

<p style="text-align:center;">
  <img id="qrcode"/>
</p>

app/views/game/about.html.erb
<p>
  Welcome all to the API Hunter site.<br/><br/>
  
  The aim of the game is to test your general knowledge of various types of the API's available around the web.<br/><br/>
  
  We will be using the most famous ones in our sites for now, i.e. Google maps, Twitter..etc.<br/><br/>
  
  The way play the game is simple. a question will be posted in which you answer by writing a piece of code utilizing the specified API to achieve the Task in question.<br/><br/>
  
  If the answer is wrong, an alert will appear to notify you, otherwise you will be taken to another page and presented with another question.<br/><br/>
  
  The Hunt contains different level of difficulty depends on your knowledge of each type of the API's.<br/><br/>
  
  It is very Straight Forward no need to explain any more so let The HUNT BEGIN!!!!!
</p>

app/views/game/google_chart_qrcode.erb
Please submit your code :
<%= form_tag google_chart_qrcode_check_game_index_path do %>
<%= text_area_tag :body , "/*

  var qrcode_content = 'I <3 API :)'
  var size = 300;

  qrcode_content = encodeURIComponent(qrcode_content);

  var url = 'http://chart.apis.google.com/chart?cht=qr'
  url += '&chs=' + size + 'x' + size
  url += '&chl=' + qrcode_content

  $('#qrcode').attr('src' , url);

*/" , style:'font-family:monospace;width:100%;height:300px;' %>
<button>SUBMIT</button>
<% end %>

app/views/game/index.html.erb
<h2 class="ans_title shake shake-slow">
Please choose your action :
</h2>
<div class="row challenges">
  <div class="col-md-4 challenge">
    <h2><i class="fa fa-twitter"></i> trends place</h2>
    <%= challenge_link(0) %>
  </div>
  <div class="col-md-4 challenge">
    <h2><i class="fa fa-twitter"></i> draw kitten</h2>
    <%= challenge_link(1) %>
  </div>
  <div class="col-md-4 challenge">
    <h2><i class="fa fa-twitter"></i> obama</h2>
    <%= challenge_link(2) %>
  </div>
  <div class="col-md-4 challenge">
    <h2><i class="fa fa-map-marker"></i> goto London</h2>
    <%= challenge_link(3) %>
  </div>
  <div class="col-md-4 challenge">
    <h2><i class="fa fa-map-marker"></i> get timezone</h2>
    <%= challenge_link(4) %>
  </div>
  <div class="col-md-4 challenge">
    <h2><i class="fa fa-map-marker"></i> ingress style</h2>
    <%= challenge_link(5) %>
  </div>
  <div class="col-md-4 challenge">
    <h2><i class="fa fa-picture-o"></i> street view</h2>
    <%= challenge_link(6) %>
  </div>
  <div class="col-md-4 challenge">
    <h2><i class="fa fa-location-arrow"></i> where am I</h2>
    <%= challenge_link(7) %>
  </div>
  <div class="col-md-4 challenge">
    <h2><i class="fa fa-qrcode"></i> QRcode</h2>
    <%= challenge_link(8) %>
  </div>
</div>

app/views/game/level.html.erb
<% content_for :css do %>
<style>
  #input_body{
    width:80%;
    height:300px;
    display:block;
    margin:0 auto;
  }
</style>
<% end %>
<% content_for :js do %>
<script>
  jQuery(function($){
$('#hint').click(function(){
  $.get('/hint/level_<%= @level %>.txt?' + Math.random() , function(data){
    $('#input_body').val(data);
  });
  return false;
});
$('#clear').click(function(){
  $('#input_body').val('');
  return false;
});

    //autoload
    $.get('/default/level_<%= @level %>.txt?' + Math.random() , function(data){
      $('#input_body').val(data);
    });

  });
</script>
<% end %>
<h2 class="ans_title shake shake-slow">Please submit your code :</h2>
<%= form_tag level_save_game_path(@level) do %>
  <%= text_area_tag :body , '' , id:'input_body' , autofocus:'autofocus' %>
  <div style="text-align:center;margin:20px;">
    <button id='submit' class='btn btx-xl btn-success'>SUBMIT</button>
    <button id='hint' class='btn btn-xl btn-warning'>hint</button>
    <button id='clear' class='btn btn-xl btn-danger'>clean</button>
  </div>
<% end %>

app/views/game/level_show.html.erb
<% content_for :js do %>
<script>
function send_success(is_success , score_id){
<% unless @score.is_callback  %>
  $.post('/game/' + score_id + '/level_callback' , {is_success : is_success ? 1 : 0} , function(data){});
  if(is_success){
    $('.check_me.check_success').show();
  }else{
    $('.check_me.check_error').show();
  }
<% end %>
}

</script>
<% end %>


<% if @score.is_callback  %>
  <% if @score.is_success %>
<h2 class="ans_title ans_title_success shake shake-slow">Congratulations!</h2>
  <% else %>
<h2 class="ans_title ans_title_fail shake shake-slow">Sorry...</h2>
  <% end %>
<% else %>
<h2 class='ans_title ans_title_success check_me check_success shake shake-slow' style="display:none !important;">
  Congratulations!
</h2>
<h2 class='ans_title ans_title_fail check_me check_error shake shake-slow' style="display:none !important;">
  Sorry...
</h2>
<% end %>
<%= render "level_show_#{@level}"%>

app/views/game/twitter_draw_kitten.html.erb
Please submit your code :
<%= form_tag twitter_draw_kitten_check_game_index_path do %>
<%= text_area_tag :body , '=begin

WIDTH = 200
HEIGHT = 300

save_path = "tmp/kitten.jpg"

file = File.open(save_path, "w")
file.write(
  open("http://placekitten.com/g/#{WIDTH}/#{HEIGHT}").read
)
file.close

file = File.open(save_path, "r")

new_twitter = $twitter_api.update_with_media(
  "kitten so cute <3",
  file
)
#File.delete(save_path)

puts new_twitter.url.to_s

=end' , style:'font-family:monospace;width:100%;height:300px;' %>
<button>SUBMIT</button>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApiHunter</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link href="/bootstrap/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="/bootstrap/css/bootstrap-theme.min.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="/font-awesome/css/font-awesome.min.css" media="screen" rel="stylesheet" type="text/css" />
  <link href='http://fonts.googleapis.com/css?family=Condiment|Source+Code+Pro:400,600|Special+Elite' rel='stylesheet' type='text/css'>
  <link href="/layout.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="/csshake.min.css" media="screen" rel="stylesheet" type="text/css" />
  <%= csrf_meta_tags %>
  <%= yield :css %>
</head>
<body>
  <div class="container">
    <h1 class="text_3d center" style="font-size:80px;margin:40px 0 30px 0;"><a href="/" style="color:#fff;text-decoration:none;">API Hunter</a><%= " : #{@title}" if @title %></h1>
    <% if current_user %>
      <span style="position:absolute;right:20px;top:20px;text-align:center;display:block;border:1px #ccc solid;border-radius:6px;padding:4px;">
        Hi <%= current_user.name %> ! <br/>
        <span style="font-size:30px;color:#009900;"><%= Score.user_score(current_user) %>%</span><br/>
        <%= link_to 'Edit profile' , profile_index_path , class:'btn btn-success btn-xs' %>
        <%= link_to 'Logout' , destroy_user_session_path , data:{method:'delete'} , class:'btn btn-warning btn-xs' %>
      </span>
    <% end %>    
<%= yield %>
  </div>
  <span style="position:absolute;left:20px;top:20px;">
    <%= link_to 'Home' , root_path , class:'btn btn-default' %>
    <%= link_to 'About' , about_game_index_path , class:'btn btn-default' %>
  </span>
  <%= javascript_include_tag 'application' %>
  <script src="/bootstrap/js/bootstrap.min.js"></script>
  <%= yield :js %>
</body>
</html>